[package]
name = "guessgame"
version = "0.1.0"
authors = ["Smaran Harihar <smaran.harihar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"